console.log("-------------------------------------------------------------------------");
console.log("----------------------------Student Report Card--------------------------")
console.log("*************************************************************************");
let name = "Name   : Akhtar Ansari";
console.log(name);
let school = "School : Govt. Boys Sr. Sec. School No.1";
console.log(school);
console.log("-------------------------------------------------------------------------");
let grade = "Grade  : A+";
console.log(grade);
let section = "Section: A";
console.log(section);
console.log("-------------------------------------------------------------------------");
let rollno = "Roll No: 21";
console.log(rollno);
let marks = "Marks  : 270";
console.log(marks);
console.log("-------------------------------------------------------------------------");
console.log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
console.log("Subject                     Obtained Mark                   Maximum Marks");
console.log("-------------------------------------------------------------------------");
console.log("Math                            90                                    100");
console.log("Science                         90                                    100");
console.log("English                         90                                    100");
console.log("-------------------------------------------------------------------------");
console.log("Total                          270                                    300");
console.log("--------------------------!!End Of Report!!------------------------------");
console.log("*****************************!!Thankyou!!********************************");
console.log("-------------------------------------------------------------------------");